-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Color exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


blue : SelectionSet Float Api.Object.Color
blue =
    Object.selectionForField "Float" "blue" [] Decode.float


green : SelectionSet Float Api.Object.Color
green =
    Object.selectionForField "Float" "green" [] Decode.float


red : SelectionSet Float Api.Object.Color
red =
    Object.selectionForField "Float" "red" [] Decode.float
