-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Project exposing (..)

import Api.Object
import Api.Scalar
import CustomScalarCodecs
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet CustomScalarCodecs.Uuid Api.Object.Project
id =
    Object.selectionForField "CustomScalarCodecs.Uuid" "id" [] (CustomScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


name : SelectionSet String Api.Object.Project
name =
    Object.selectionForField "String" "name" [] Decode.string


short : SelectionSet String Api.Object.Project
short =
    Object.selectionForField "String" "short" [] Decode.string


backlogs :
    SelectionSet decodesTo Api.Object.Backlog
    -> SelectionSet (List decodesTo) Api.Object.Project
backlogs object____ =
    Object.selectionForCompositeField "backlogs" [] object____ (Basics.identity >> Decode.list)
