-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.InputObject exposing (..)

import Api.Enum.Importance
import Api.Enum.IssueType
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


buildIssueCreateInput :
    IssueCreateInputRequiredFields
    -> (IssueCreateInputOptionalFields -> IssueCreateInputOptionalFields)
    -> IssueCreateInput
buildIssueCreateInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { epic = Absent, state = Absent }
    in
    { backlog = required____.backlog, description = required____.description, epic = optionals____.epic, importance = required____.importance, name = required____.name, points = required____.points, state = optionals____.state, type_ = required____.type_ }


type alias IssueCreateInputRequiredFields =
    { backlog : CustomScalarCodecs.Uuid
    , description : String
    , importance : Api.Enum.Importance.Importance
    , name : String
    , points : Int
    , type_ : Api.Enum.IssueType.IssueType
    }


type alias IssueCreateInputOptionalFields =
    { epic : OptionalArgument CustomScalarCodecs.Uuid
    , state : OptionalArgument CustomScalarCodecs.Uuid
    }


{-| Type for the IssueCreateInput input object.
-}
type alias IssueCreateInput =
    { backlog : CustomScalarCodecs.Uuid
    , description : String
    , epic : OptionalArgument CustomScalarCodecs.Uuid
    , importance : Api.Enum.Importance.Importance
    , name : String
    , points : Int
    , state : OptionalArgument CustomScalarCodecs.Uuid
    , type_ : Api.Enum.IssueType.IssueType
    }


{-| Encode a IssueCreateInput into a value that can be used as an argument.
-}
encodeIssueCreateInput : IssueCreateInput -> Value
encodeIssueCreateInput input____ =
    Encode.maybeObject
        [ ( "backlog", (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecUuid) input____.backlog |> Just ), ( "description", Encode.string input____.description |> Just ), ( "epic", (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecUuid) |> Encode.optional input____.epic ), ( "importance", Encode.enum Api.Enum.Importance.toString input____.importance |> Just ), ( "name", Encode.string input____.name |> Just ), ( "points", Encode.int input____.points |> Just ), ( "state", (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecUuid) |> Encode.optional input____.state ), ( "type", Encode.enum Api.Enum.IssueType.toString input____.type_ |> Just ) ]


buildIssueUpdateInput :
    IssueUpdateInputRequiredFields
    -> (IssueUpdateInputOptionalFields -> IssueUpdateInputOptionalFields)
    -> IssueUpdateInput
buildIssueUpdateInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { description = Absent, epic = Absent, importance = Absent, name = Absent, points = Absent, state = Absent }
    in
    { description = optionals____.description, epic = optionals____.epic, id = required____.id, importance = optionals____.importance, name = optionals____.name, points = optionals____.points, state = optionals____.state }


type alias IssueUpdateInputRequiredFields =
    { id : CustomScalarCodecs.Uuid }


type alias IssueUpdateInputOptionalFields =
    { description : OptionalArgument String
    , epic : OptionalArgument CustomScalarCodecs.Uuid
    , importance : OptionalArgument Api.Enum.Importance.Importance
    , name : OptionalArgument String
    , points : OptionalArgument Int
    , state : OptionalArgument CustomScalarCodecs.Uuid
    }


{-| Type for the IssueUpdateInput input object.
-}
type alias IssueUpdateInput =
    { description : OptionalArgument String
    , epic : OptionalArgument CustomScalarCodecs.Uuid
    , id : CustomScalarCodecs.Uuid
    , importance : OptionalArgument Api.Enum.Importance.Importance
    , name : OptionalArgument String
    , points : OptionalArgument Int
    , state : OptionalArgument CustomScalarCodecs.Uuid
    }


{-| Encode a IssueUpdateInput into a value that can be used as an argument.
-}
encodeIssueUpdateInput : IssueUpdateInput -> Value
encodeIssueUpdateInput input____ =
    Encode.maybeObject
        [ ( "description", Encode.string |> Encode.optional input____.description ), ( "epic", (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecUuid) |> Encode.optional input____.epic ), ( "id", (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecUuid) input____.id |> Just ), ( "importance", Encode.enum Api.Enum.Importance.toString |> Encode.optional input____.importance ), ( "name", Encode.string |> Encode.optional input____.name ), ( "points", Encode.int |> Encode.optional input____.points ), ( "state", (CustomScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecUuid) |> Encode.optional input____.state ) ]
