-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Backlog
    = Backlog


type Epic
    = Epic


type Issue
    = Issue


type Project
    = Project


type State
    = State
